### ISSUE TITLE
Confidential information leaked

### ISSUE THREAD

**Issue by aravindvnair99** [techgod/PESBOT#1]
https://github.com/techgod/PESBOT/blob/729b5a04546276ef36f5162c1647946c9336ecac/venv/serviceAccountKey.json#L5

Suggestion: Remove confidential information, generate a new key and use a `.gitignore` file

**Comment by techgod** [comment]
Oh yea xD
I'm actually going to go ahead and delete this repo itself, will duplicate another version.
Thanks though! (Also not sure if you're going to see this after I delete it!) XD

**Comment by aravindvnair99** [comment]
> Oh yea xD
> I'm actually going to go ahead and delete this repo itself, will duplicate another version.
> Thanks though! (Also not sure if you're going to see this after I delete it!) XD

@techgod  Haha no issues, I've seen your reply. Comes via email too!

**Comment by aravindvnair99** [comment]
@techgod You just need to regenerate the service account and add the .gitignore by the way. Deletion isn't necessary.
